CREATE DATABASE task_db;
USE task_db;

CREATE TABLE task(
	id_task INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(200) NOT NULL,
	priority VARCHAR(200) NOT NULL,
    description VARCHAR(200) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;

CREATE TABLE productos(
	id_producto INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	nombre VARCHAR(100) NOT NULL,
    imagen VARCHAR(200) NOT NULL,
	descripcion VARCHAR(200) NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;